further adaptations

diff --git a/script/cibuild-ccql-build-deploy-tarball b/script/cibuild-ccql-build-deploy-tarball
--- a/script/cibuild-ccql-build-deploy-tarball
+++ b/script/cibuild-ccql-build-deploy-tarball
@@ -1,40 +1,47 @@
-#!/bin/sh
+#!/bin/bash
 
-set -e
+output_fold() {
+  # Exit early if no label provided
+  if [ -z "$1" ]; then
+    echo "output_fold(): requires a label argument."
+    return
+  fi
 
-echo "Building"
-script/build
+  exit_value=0  # exit_value is used to record exit status of the given command
+  label=$1      # human-readable label describing what's being folded up
+  shift 1       # having retrieved the output_fold()-specific arguments, strip them off $@
 
-cd .gopath/src/github.com/github/ccql
+  # Only echo the tags when in CI_MODE
+  if [ "$CI_MODE" ]; then
+    echo "%%%FOLD {$label}%%%"
+  fi
 
-# Get a fresh directory and make sure to delete it afterwards
-build_dir=tmp/build
-rm -rf $build_dir
-mkdir -p $build_dir
-trap "rm -rf $build_dir" EXIT
+  # run the remaining arguments. If the command exits non-0, the `||` will
+  # prevent the `-e` flag from seeing the failure exit code, and we'll see
+  # the second echo execute
+  "$@" || exit_value=$?
 
-commit_sha=$(git rev-parse HEAD)
+  # Only echo the tags when in CI_MODE
+  if [ "$CI_MODE" ]; then
+    echo "%%%END FOLD%%%"
+  fi
 
-if [ $(uname -s) = "Darwin" ]; then
-    build_arch="$(uname -sr | tr -d ' ' | tr '[:upper:]' '[:lower:]')-$(uname -m)"
-else
-    build_arch="$(lsb_release -sc | tr -d ' ' | tr '[:upper:]' '[:lower:]')-$(uname -m)"
-fi
+  # preserve the exit code from the subcommand.
+  return $exit_value
+}
 
-tarball=$build_dir/${commit_sha}-${build_arch}.tar
+function cleanup() {
+  echo
+  echo "%%%FOLD {Shutting down services...}%%%"
+  docker-compose down
+  echo "%%%END FOLD%%%"
+}
 
-# Create the tarball
-tar cvf $tarball --mode="ugo=rx" bin/
+trap cleanup EXIT
 
-# Compress it and copy it to the directory for the CI to upload it
-gzip $tarball
-mkdir -p "$BUILD_ARTIFACT_DIR"/ccql
-cp ${tarball}.gz "$BUILD_ARTIFACT_DIR"/ccql/
+export CI_MODE=true
 
-### HACK HACK HACK ###
-# blame @carlosmn
-# We don't have any jessie machines for building, but a pure-Go binary depends
-# on a version of libc and ld which are widely available, so we can copy the
-# tarball over with jessie in its name so we can deploy it on jessie machines.
-jessie_tarball_name=$(echo $(basename "${tarball}") | sed s/-precise-/-jessie-/)
-cp ${tarball}.gz "$BUILD_ARTIFACT_DIR/ccql/${jessie_tarball_name}.gz"
+output_fold "Bootstrapping container..." docker-compose build
+output_fold "Running tests..." docker-compose run --rm app
+
+docker-compose -e BUILD_ARTIFACT_DIR=$BUILD_ARTIFACT_DIR -v $BUILD_ARTIFACT_DIR:$BUILD_ARTIFACT_DIR app script/build-deploy-tarball
