Updating script/cibuild

diff --git a/script/cibuild b/script/cibuild
--- a/script/cibuild
+++ b/script/cibuild
@@ -1,17 +1,45 @@
 #!/bin/bash
 
-set -e
+output_fold() {
+  # Exit early if no label provided
+  if [ -z "$1" ]; then
+    echo "output_fold(): requires a label argument."
+    return
+  fi
 
-. script/bootstrap
+  exit_value=0  # exit_value is used to record exit status of the given command
+  label=$1      # human-readable label describing what's being folded up
+  shift 1       # having retrieved the output_fold()-specific arguments, strip them off $@
 
-echo "Verifying code is formatted via 'gofmt -s -w  go/'"
-gofmt -s -w  go/
-git diff --exit-code --quiet
+  # Only echo the tags when in CI_MODE
+  if [ "$CI_MODE" ]; then
+    echo "%%%FOLD {$label}%%%"
+  fi
 
-echo "Building"
-script/build
+  # run the remaining arguments. If the command exits non-0, the `||` will
+  # prevent the `-e` flag from seeing the failure exit code, and we'll see
+  # the second echo execute
+  "$@" || exit_value=$?
 
-cd .gopath/src/github.com/github/ccql
+  # Only echo the tags when in CI_MODE
+  if [ "$CI_MODE" ]; then
+    echo "%%%END FOLD%%%"
+  fi
 
-echo "Running unit tests"
-go test ./go/...
+  # preserve the exit code from the subcommand.
+  return $exit_value
+}
+
+function cleanup() {
+  echo
+  echo "%%%FOLD {Shutting down services...}%%%"
+  docker-compose down
+  echo "%%%END FOLD%%%"
+}
+
+trap cleanup EXIT
+
+export CI_MODE=true
+
+output_fold "Bootstrapping container..." docker-compose build
+output_fold "Running tests..." docker-compose run --rm app
